---
title: 'Spatial distribution - Section 3'
author: "Rudolf Schlechter"
output: 
    html_document:
        df_print: paged
        keep_md: yes
    pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center', dpi = 300, cache = TRUE)
options(digits = 2, scipen = 1, pillar.signif = 3)

library(here)
library(tidyverse)

set.seed(19900725)
```

### Effect of community complexity on interspecific spatial correlations

We investigated the effect of community complexity on interspecific interactions by determining the co-aggregation frequencies of pairs of species in different treatments (S2 and S3) and sampling times (7 and 14 dpi). Co-aggregation was determined through pair cross correlations at a given distance, g(r), between pairs of strains (Fig. 7a, Fig. S4). Frequencies were then determined from all replicates and the area under the curve was used as a measure to compare aggregation patterns of pairs of species in S3 relative to S2 communities.

We noticed that the frequencies of co-aggregation were generally lower than those observed from within-population aggregation. However, co-aggregation was detected in every strain pair in S2 communities at each sampling point (Fig. S4). In general, the presence of a third strain decreased these co-aggregation frequencies. We observed that co-aggregation was 23% lower in S3 than S2 at 7 dpi (one sample t-test, t29 = -2.37, p = 0.024), but became comparable at 14 dpi (Fig. 7b, one sample t-test, t29 = 0.66, p = 0.51). Co-aggregation at 14 dpi was higher than at 7 dpi in S3 (two sample t-test, t58 = -2.09, p = 0.041).

We determined the maximal frequency of co-aggregation for each bacterial pair, which was generally observed at a ~1.5 μm distance between cells (Fig. 7a, Fig. S4). We observed an increase of co-aggregation over time, as maximal co-aggregation frequencies increased from 20.3 ± 12.6% to 40.8 ± 16.5% at 7 and 14 dpi, respectively (Fig. 7c). 

In general, we observed that co-aggregation frequencies decreased rapidly after 1.5 μm. Since co-aggregation was detected at every distance range (Fig. S5a), we focused on the differences in co-aggregation only within the 0–10 μm distance interval instead of the maximal range of co-aggregation. Based on the empirical cumulative distribution function (Fig. S5b), 64% of the co-aggregation pattern was observed at a distance equal or less than 10 μm, in which the maximal frequency of co-aggregation was captured. We observed that at 14 dpi, a high percentage of bacterial pairs (66.6%) co-aggregated up to 10 μm, in comparison to 53.1% at 7 dpi (Fig. 7d, F1,71 = 17.79, p < 0.05). Although no differences were observed between S2 and S3 (F1,71 = 2.57, p = 0.11), we noticed that the initial variation in co-aggregation distances in S3 was markedly higher compared to S2 after 7 days (Fig. 7e). After 14 days, the variation in co-aggregation distances in S3 decreased and was comparable to S2 treatments. 

Our results indicate that the low co-aggregation and increased randomness observed in more complex communities are only transitional, as from 7 to 14 dpi, co-aggregation between pairs in presence of a third strain are comparable to conditions where only these pairs were present in the phyllosphere.
